<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyTitle>osu! Collection Manager CLI</AssemblyTitle>
		<Copyright>Copyright © 2017-present Piotrekol</Copyright>
		<PackageId>CollectionManager.App.Cli</PackageId>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CollectionManager.Core\CollectionManager.Core.csproj" />
		<ProjectReference Include="..\CollectionManager.Extensions\CollectionManager.Extensions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommandLineParser" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>
</Project>
